In [5]:
import numpy as np
"""
i) Write a code to generate five random vectors a1, a2, a3, a4, a5 ∈R5
and verify that these set of vectors are linearly independent.
"""
a1=np.random.rand(5)
a2=np.random.rand(5)
a3=np.random.rand(5)
a4=np.random.rand(5)
a5=np.random.rand(5)
#a5=np.random.randint(0, 10, size=[5,1])
"""
print("a1: \n",a1)
print("a2: \n",a2)
print("a3: \n",a3)
print("a4: \n",a4)
print("a5: \n",a5)
"""
A = np.array([a1,a2,a3,a4,a5])
detOfA=np.linalg.det(A)
if detOfA == 0:
    print("Linearly Dependent")
else:
    print("Linearly independent")

Linearly independent


In [6]:
"""
ii) Write a function that applies Gram-Schmidt Algorithm on the
set of vectors a1, a2, a3, a4, a5. Let the output of Gram Schmidt
algorithm be the vectors q1, q2, q3, q4, q5.
"""
def grm_schmidt(aA):
    QMatrix = np.zeros_like(aA)
    cMatrix = np.zeros_like(aA[0])
    for i in range(len(aA)):
        cMatrix=aA[i]
        for j in range(i):
            cMatrix-=np.dot(QMatrix[j],aA[i] * QMatrix[j])
            QMatrix[i]= cMatrix/np.linalg.norm(cMatrix)

    return QMatrix
print(A)
Q = grm_schmidt(A)
print("Gram_Schmidt Output")
print(Q)

[[0.9574661  0.59780324 0.11965635 0.9400401  0.15528495]
 [0.12634045 0.23401916 0.70613669 0.05811015 0.87234526]
 [0.27667626 0.80605506 0.40175381 0.92900563 0.41458766]
 [0.08715156 0.45138297 0.55282335 0.41961363 0.99464357]
 [0.36270555 0.79563377 0.28341477 0.96206709 0.95096511]]
Gram_Schmidt Output
[[ 0.          0.          0.          0.          0.        ]
 [ 0.10939822  0.20263724  0.6114439   0.05031759  0.75536394]
 [-0.22935086  0.58638298 -0.03661554  0.77584078 -0.01683952]
 [-0.47831244  0.05570167  0.20442743  0.00912339  0.85219758]
 [-0.60608515  0.01087433 -0.71908125  0.24805594  0.23223469]]


In [7]:
"""
iii) Write a code to create a matrix Q ∈ R5×5 with q1, q2, q3, q4, q5
as the five columns. Then create a matrix B = Q⊤Q.
"""
#print("Q transpose")
#B = Q.T
B=Q.T.dot(Q)
print("Transpose output")
print(B)

Transpose output
[[ 0.66069179 -0.14555286  0.41333296 -0.32714195 -0.46187307]
 [-0.14555286  0.38812778  0.10599799  0.46834168  0.19318468]
 [ 0.41333296  0.10599799  0.93407276 -0.17414875  0.46969621]
 [-0.32714195  0.46834168 -0.17414875  0.66607576  0.09032543]
 [-0.46187307  0.19318468  0.46969621  0.09032543  1.35103191]]


In [8]:
"""
iv) Write a code to calculate the value of ∥B − I5∥F where ∥ · ∥F is
the matrix Frobenius norm.
"""
Imatrix = np.identity(5,dtype="int")
#print("Identity matrix")
#print(Imatrix)
print("matrix Frobenius norm")
print(np.linalg.norm(B-Imatrix,'fro'))

matrix Frobenius norm
1.6755152204675439
